name: klaam
channels:
  - defaults
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.8
  - poetry
  # klaam dependencies
  - librosa
  - ffmpeg
  - cudatoolkit
  - pytorch
  - torchaudio
